name: Build and Release Extension

on:
  push:
    branches:
      - main
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install pnpm and dependencies, build extension
        run: |
          npm install -g pnpm  
          pnpm install --frozen-lockfile
          pnpm run build

      - name: Rename folder before zipping
        run: |
          mv ./build/chrome-mv3-prod ./build/my-extension-folder

      - name: Create .zip package
        run: |
          zip -r plasmo-extension.zip ./build/my-extension-folder/*

      - name: Create GitHub Release and Upload .zip
        uses: softprops/action-gh-release@v2.2.1
        with:
          files: plasmo-extension.zip
